networks:
  certy:
    external: false

services:
  certy:
    image: ghcr.io/chriskacerguis/certy:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=certy.domain.com
      - VIRTUAL_PORT=3000
    volumes:
      - certy_data:/app/.local-ca
    depends_on:
      - pocket-id
    networks:
      - certy

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    volumes:
      - "pocket_data:/app/data"
    environment:
      - VIRTUAL_HOST=oidc.domain.com
      - VIRTUAL_PORT=1411
      - APP_URL=https://oidc.domain.com
      - TRUST_PROXY=false
      - MAXMIND_LICENSE_KEY=
      - PUID=1000
      - PGID=1000
    networks:
      - certy

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./cert.pem:/etc/nginx/certs/domain.com.crt:ro
      - ./key.des.pem:/etc/nginx/certs/domain.com.key:ro
    networks:
      - certy

volumes:
  certy_data:
  pocket_data:
