services:

  # certy:
  #   build: .
  #   container_name: certy
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - dev-oidc

  dev-oidc:
    image: ghcr.io/businesssimulations/dev-oidc-toolkit:latest
    container_name: dev-oidc
    ports:
      - "8080:8080"
    environment:
      # Define a test user
      - DevOidcToolkit__Users__0__Email=test@localhost
      - DevOidcToolkit__Users__0__FirstName=Test
      - DevOidcToolkit__Users__0__LastName=User
      # Define a client for your Express app
      - DevOidcToolkit__Clients__0__Id=client
      - DevOidcToolkit__Clients__0__Secret=secret
      - DevOidcToolkit__Clients__0__RedirectUris__0=http://localhost:3000/auth/callback
